[package]
name = "voltage_codegen"
version = "0.1.0"
edition = "2021"

[features]
json_abi = []

[dependencies]
serde = { version = "1.0.171", features = ["derive"] }
serde_json = "1.0.100"
voltage_ast = { version = "0.1.0", path = "../voltage_ast" }
